
/*
 * Copyright (c) 2016-2018, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted (subject to the limitations in the
 * disclaimer below) provided that the following conditions are met:
 *
 *    * Redistributions of source code must retain the above copyright
 *      notice, this list of conditions and the following disclaimer.
 *
 *    * Redistributions in binary form must reproduce the above
 *      copyright notice, this list of conditions and the following
 *      disclaimer in the documentation and/or other materials provided
 *      with the distribution.
 *
 *    * Neither the name of The Linux Foundation nor the names of its
 *      contributors may be used to endorse or promote products derived
 *      from this software without specific prior written permission.
 *
 * NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE
 * GRANTED BY THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT
 * HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
 * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE
 * GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER
 * IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
 * OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
 * IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "graph_app.h"

#define MAX_LABELS 1024
#define WORD_SIZE 50

char *default_categories[];
char **categories;
int num_labels;

struct indexed_data {
	float f;
	int i;
};

int indexed_data_sort(const void *va, const void *vb)
{
	const struct indexed_data *a = va; 
	const struct indexed_data *b = vb; 
	if (a->f > b->f) return -1;
	if (a->f < b->f) return 1;
	return 0;
}

int load_labels(const char *labels_filename) {
	FILE *labels_file = NULL;
	int i;

	if ((labels_file = fopen(labels_filename,"rb")) == NULL) {
		printf("File not found: %s , not printing top5...\n",labels_filename);
		return 1;
	}
	if ((categories = malloc(sizeof(char*) * MAX_LABELS)) == NULL) {
        printf("Malloc failed, not printing top5...\n");
		return 1;
    }
	memset(categories,0,sizeof(char*) * MAX_LABELS);
	i = 0;
	while (i < MAX_LABELS) {
		if ((categories[i] = malloc(sizeof(char) * WORD_SIZE)) == NULL) {
			printf("Malloc failed, not printing top5...\n");
			return 1;
		}
        memset(categories[i], 0, sizeof(char) * WORD_SIZE);
        if(fgets(categories[i], WORD_SIZE, labels_file) == NULL)
        	break;
        i++;
 	}
 	num_labels = i + 1;
 	fclose(labels_file);
 	return 0;
}

void free_labels() {
	for (int i = 0; i < num_labels; i++) {
		free(categories[i]);
	}
	free(categories);
}

void top5(float *data, int length)
{
	struct indexed_data *tmp;
	int i;

	if ((tmp = malloc(sizeof(struct indexed_data)*length)) == NULL) {
		printf("Malloc failed, not printing top5...\n");
		return;
	}
	for (i = 0; i < length; i++) {
		tmp[i].f = data[i];
		tmp[i].i = i;
	}
	qsort(tmp,length,sizeof(*tmp),indexed_data_sort);
	
	if (!categories) {
		categories = default_categories;
		num_labels = MAX_LABELS;
	}

	printf("%s,%s,%s,%s\n","Rank","Softmax","index","string");
	for (i = 0; i < 5; i++) {
		int index = tmp[i].i;
		if ((index >= 0) && (index < num_labels)) {
			printf("%d,%f,%d,%s",i,tmp[i].f,index,categories[index]);
		} else {
			printf("ERROR: Index %d is out of range\n",index);
		}
	}
	free(tmp);
}


char *default_categories[] = {
"dummy\n",
"kit fox\n",
"English setter\n",
"Siberian husky\n",
"Australian terrier\n",
"English springer\n",
"grey whale\n",
"lesser panda\n",
"Egyptian cat\n",
"ibex\n",
"Persian cat\n",
"cougar\n",
"gazelle\n",
"porcupine\n",
"sea lion\n",
"malamute\n",
"badger\n",
"Great Dane\n",
"Walker hound\n",
"Welsh springer spaniel\n",
"whippet\n",
"Scottish deerhound\n",
"killer whale\n",
"mink\n",
"African elephant\n",
"Weimaraner\n",
"soft-coated wheaten terrier\n",
"Dandie Dinmont\n",
"red wolf\n",
"Old English sheepdog\n",
"jaguar\n",
"otterhound\n",
"bloodhound\n",
"Airedale\n",
"hyena\n",
"meerkat\n",
"giant schnauzer\n",
"titi\n",
"three-toed sloth\n",
"sorrel\n",
"black-footed ferret\n",
"dalmatian\n",
"black-and-tan coonhound\n",
"papillon\n",
"skunk\n",
"Staffordshire bullterrier\n",
"Mexican hairless\n",
"Bouvier des Flandres\n",
"weasel\n",
"miniature poodle\n",
"Cardigan\n",
"malinois\n",
"bighorn\n",
"fox squirrel\n",
"colobus\n",
"tiger cat\n",
"Lhasa\n",
"impala\n",
"coyote\n",
"Yorkshire terrier\n",
"Newfoundland\n",
"brown bear\n",
"red fox\n",
"Norwegian elkhound\n",
"Rottweiler\n",
"hartebeest\n",
"Saluki\n",
"grey fox\n",
"schipperke\n",
"Pekinese\n",
"Brabancon griffon\n",
"West Highland white terrier\n",
"Sealyham terrier\n",
"guenon\n",
"mongoose\n",
"indri\n",
"tiger\n",
"Irish wolfhound\n",
"wild boar\n",
"EntleBucher\n",
"zebra\n",
"ram\n",
"French bulldog\n",
"orangutan\n",
"basenji\n",
"leopard\n",
"Bernese mountain dog\n",
"Maltese dog\n",
"Norfolk terrier\n",
"toy terrier\n",
"vizsla\n",
"cairn\n",
"squirrel monkey\n",
"groenendael\n",
"clumber\n",
"Siamese cat\n",
"chimpanzee\n",
"komondor\n",
"Afghan hound\n",
"Japanese spaniel\n",
"proboscis monkey\n",
"guinea pig\n",
"white wolf\n",
"ice bear\n",
"gorilla\n",
"borzoi\n",
"toy poodle\n",
"Kerry blue terrier\n",
"ox\n",
"Scotch terrier\n",
"Tibetan mastiff\n",
"spider monkey\n",
"Doberman\n",
"Boston bull\n",
"Greater Swiss Mountain dog\n",
"Appenzeller\n",
"Shih-Tzu\n",
"Irish water spaniel\n",
"Pomeranian\n",
"Bedlington terrier\n",
"warthog\n",
"Arabian camel\n",
"siamang\n",
"miniature schnauzer\n",
"collie\n",
"golden retriever\n",
"Irish terrier\n",
"affenpinscher\n",
"Border collie\n",
"hare\n",
"boxer\n",
"silky terrier\n",
"beagle\n",
"Leonberg\n",
"German short-haired pointer\n",
"patas\n",
"dhole\n",
"baboon\n",
"macaque\n",
"Chesapeake Bay retriever\n",
"bull mastiff\n",
"kuvasz\n",
"capuchin\n",
"pug\n",
"curly-coated retriever\n",
"Norwich terrier\n",
"flat-coated retriever\n",
"hog\n",
"keeshond\n",
"Eskimo dog\n",
"Brittany spaniel\n",
"standard poodle\n",
"Lakeland terrier\n",
"snow leopard\n",
"Gordon setter\n",
"dingo\n",
"standard schnauzer\n",
"hamster\n",
"Tibetan terrier\n",
"Arctic fox\n",
"wire-haired fox terrier\n",
"basset\n",
"water buffalo\n",
"American black bear\n",
"Angora\n",
"bison\n",
"howler monkey\n",
"hippopotamus\n",
"chow\n",
"giant panda\n",
"American Staffordshire terrier\n",
"Shetland sheepdog\n",
"Great Pyrenees\n",
"Chihuahua\n",
"tabby\n",
"marmoset\n",
"Labrador retriever\n",
"Saint Bernard\n",
"armadillo\n",
"Samoyed\n",
"bluetick\n",
"redbone\n",
"polecat\n",
"marmot\n",
"kelpie\n",
"gibbon\n",
"llama\n",
"miniature pinscher\n",
"wood rabbit\n",
"Italian greyhound\n",
"lion\n",
"cocker spaniel\n",
"Irish setter\n",
"dugong\n",
"Indian elephant\n",
"beaver\n",
"Sussex spaniel\n",
"Pembroke\n",
"Blenheim spaniel\n",
"Madagascar cat\n",
"Rhodesian ridgeback\n",
"lynx\n",
"African hunting dog\n",
"langur\n",
"Ibizan hound\n",
"timber wolf\n",
"cheetah\n",
"English foxhound\n",
"briard\n",
"sloth bear\n",
"Border terrier\n",
"German shepherd\n",
"otter\n",
"koala\n",
"tusker\n",
"echidna\n",
"wallaby\n",
"platypus\n",
"wombat\n",
"revolver\n",
"umbrella\n",
"schooner\n",
"soccer ball\n",
"accordion\n",
"ant\n",
"starfish\n",
"chambered nautilus\n",
"grand piano\n",
"laptop\n",
"strawberry\n",
"airliner\n",
"warplane\n",
"airship\n",
"balloon\n",
"space shuttle\n",
"fireboat\n",
"gondola\n",
"speedboat\n",
"lifeboat\n",
"canoe\n",
"yawl\n",
"catamaran\n",
"trimaran\n",
"container ship\n",
"liner\n",
"pirate\n",
"aircraft carrier\n",
"submarine\n",
"wreck\n",
"half track\n",
"tank\n",
"missile\n",
"bobsled\n",
"dogsled\n",
"bicycle-built-for-two\n",
"mountain bike\n",
"freight car\n",
"passenger car\n",
"barrow\n",
"shopping cart\n",
"motor scooter\n",
"forklift\n",
"electric locomotive\n",
"steam locomotive\n",
"amphibian\n",
"ambulance\n",
"beach wagon\n",
"cab\n",
"convertible\n",
"jeep\n",
"limousine\n",
"minivan\n",
"Model T\n",
"racer\n",
"sports car\n",
"go-kart\n",
"golfcart\n",
"moped\n",
"snowplow\n",
"fire engine\n",
"garbage truck\n",
"pickup\n",
"tow truck\n",
"trailer truck\n",
"moving van\n",
"police van\n",
"recreational vehicle\n",
"streetcar\n",
"snowmobile\n",
"tractor\n",
"mobile home\n",
"tricycle\n",
"unicycle\n",
"horse cart\n",
"jinrikisha\n",
"oxcart\n",
"bassinet\n",
"cradle\n",
"crib\n",
"four-poster\n",
"bookcase\n",
"china cabinet\n",
"medicine chest\n",
"chiffonier\n",
"table lamp\n",
"file\n",
"park bench\n",
"barber chair\n",
"throne\n",
"folding chair\n",
"rocking chair\n",
"studio couch\n",
"toilet seat\n",
"desk\n",
"pool table\n",
"dining table\n",
"entertainment center\n",
"wardrobe\n",
"Granny Smith\n",
"orange\n",
"lemon\n",
"fig\n",
"pineapple\n",
"banana\n",
"jackfruit\n",
"custard apple\n",
"pomegranate\n",
"acorn\n",
"hip\n",
"ear\n",
"rapeseed\n",
"corn\n",
"buckeye\n",
"organ\n",
"upright\n",
"chime\n",
"drum\n",
"gong\n",
"maraca\n",
"marimba\n",
"steel drum\n",
"banjo\n",
"cello\n",
"violin\n",
"harp\n",
"acoustic guitar\n",
"electric guitar\n",
"cornet\n",
"French horn\n",
"trombone\n",
"harmonica\n",
"ocarina\n",
"panpipe\n",
"bassoon\n",
"oboe\n",
"sax\n",
"flute\n",
"daisy\n",
"yellow lady's slipper\n",
"cliff\n",
"valley\n",
"alp\n",
"volcano\n",
"promontory\n",
"sandbar\n",
"coral reef\n",
"lakeside\n",
"seashore\n",
"geyser\n",
"hatchet\n",
"cleaver\n",
"letter opener\n",
"plane\n",
"power drill\n",
"lawn mower\n",
"hammer\n",
"corkscrew\n",
"can opener\n",
"plunger\n",
"screwdriver\n",
"shovel\n",
"plow\n",
"chain saw\n",
"cock\n",
"hen\n",
"ostrich\n",
"brambling\n",
"goldfinch\n",
"house finch\n",
"junco\n",
"indigo bunting\n",
"robin\n",
"bulbul\n",
"jay\n",
"magpie\n",
"chickadee\n",
"water ouzel\n",
"kite\n",
"bald eagle\n",
"vulture\n",
"great grey owl\n",
"black grouse\n",
"ptarmigan\n",
"ruffed grouse\n",
"prairie chicken\n",
"peacock\n",
"quail\n",
"partridge\n",
"African grey\n",
"macaw\n",
"sulphur-crested cockatoo\n",
"lorikeet\n",
"coucal\n",
"bee eater\n",
"hornbill\n",
"hummingbird\n",
"jacamar\n",
"toucan\n",
"drake\n",
"red-breasted merganser\n",
"goose\n",
"black swan\n",
"white stork\n",
"black stork\n",
"spoonbill\n",
"flamingo\n",
"American egret\n",
"little blue heron\n",
"bittern\n",
"crane\n",
"limpkin\n",
"American coot\n",
"bustard\n",
"ruddy turnstone\n",
"red-backed sandpiper\n",
"redshank\n",
"dowitcher\n",
"oystercatcher\n",
"European gallinule\n",
"pelican\n",
"king penguin\n",
"albatross\n",
"great white shark\n",
"tiger shark\n",
"hammerhead\n",
"electric ray\n",
"stingray\n",
"barracouta\n",
"coho\n",
"tench\n",
"goldfish\n",
"eel\n",
"rock beauty\n",
"anemone fish\n",
"lionfish\n",
"puffer\n",
"sturgeon\n",
"gar\n",
"loggerhead\n",
"leatherback turtle\n",
"mud turtle\n",
"terrapin\n",
"box turtle\n",
"banded gecko\n",
"common iguana\n",
"American chameleon\n",
"whiptail\n",
"agama\n",
"frilled lizard\n",
"alligator lizard\n",
"Gila monster\n",
"green lizard\n",
"African chameleon\n",
"Komodo dragon\n",
"triceratops\n",
"African crocodile\n",
"American alligator\n",
"thunder snake\n",
"ringneck snake\n",
"hognose snake\n",
"green snake\n",
"king snake\n",
"garter snake\n",
"water snake\n",
"vine snake\n",
"night snake\n",
"boa constrictor\n",
"rock python\n",
"Indian cobra\n",
"green mamba\n",
"sea snake\n",
"horned viper\n",
"diamondback\n",
"sidewinder\n",
"European fire salamander\n",
"common newt\n",
"eft\n",
"spotted salamander\n",
"axolotl\n",
"bullfrog\n",
"tree frog\n",
"tailed frog\n",
"whistle\n",
"wing\n",
"paintbrush\n",
"hand blower\n",
"oxygen mask\n",
"snorkel\n",
"loudspeaker\n",
"microphone\n",
"screen\n",
"mouse\n",
"electric fan\n",
"oil filter\n",
"strainer\n",
"space heater\n",
"stove\n",
"guillotine\n",
"barometer\n",
"rule\n",
"odometer\n",
"scale\n",
"analog clock\n",
"digital clock\n",
"wall clock\n",
"hourglass\n",
"sundial\n",
"parking meter\n",
"stopwatch\n",
"digital watch\n",
"stethoscope\n",
"syringe\n",
"magnetic compass\n",
"binoculars\n",
"projector\n",
"sunglasses\n",
"loupe\n",
"radio telescope\n",
"bow\n",
"cannon [ground]\n",
"assault rifle\n",
"rifle\n",
"projectile\n",
"computer keyboard\n",
"typewriter keyboard\n",
"crane\n",
"lighter\n",
"abacus\n",
"cash machine\n",
"slide rule\n",
"desktop computer\n",
"hand-held computer\n",
"notebook\n",
"web site\n",
"harvester\n",
"thresher\n",
"printer\n",
"slot\n",
"vending machine\n",
"sewing machine\n",
"joystick\n",
"switch\n",
"hook\n",
"car wheel\n",
"paddlewheel\n",
"pinwheel\n",
"potter's wheel\n",
"gas pump\n",
"carousel\n",
"swing\n",
"reel\n",
"radiator\n",
"puck\n",
"hard disc\n",
"sunglass\n",
"pick\n",
"car mirror\n",
"solar dish\n",
"remote control\n",
"disk brake\n",
"buckle\n",
"hair slide\n",
"knot\n",
"combination lock\n",
"padlock\n",
"nail\n",
"safety pin\n",
"screw\n",
"muzzle\n",
"seat belt\n",
"ski\n",
"candle\n",
"jack-o'-lantern\n",
"spotlight\n",
"torch\n",
"neck brace\n",
"pier\n",
"tripod\n",
"maypole\n",
"mousetrap\n",
"spider web\n",
"trilobite\n",
"harvestman\n",
"scorpion\n",
"black and gold garden spider\n",
"barn spider\n",
"garden spider\n",
"black widow\n",
"tarantula\n",
"wolf spider\n",
"tick\n",
"centipede\n",
"isopod\n",
"Dungeness crab\n",
"rock crab\n",
"fiddler crab\n",
"king crab\n",
"American lobster\n",
"spiny lobster\n",
"crayfish\n",
"hermit crab\n",
"tiger beetle\n",
"ladybug\n",
"ground beetle\n",
"long-horned beetle\n",
"leaf beetle\n",
"dung beetle\n",
"rhinoceros beetle\n",
"weevil\n",
"fly\n",
"bee\n",
"grasshopper\n",
"cricket\n",
"walking stick\n",
"cockroach\n",
"mantis\n",
"cicada\n",
"leafhopper\n",
"lacewing\n",
"dragonfly\n",
"damselfly\n",
"admiral\n",
"ringlet\n",
"monarch\n",
"cabbage butterfly\n",
"sulphur butterfly\n",
"lycaenid\n",
"jellyfish\n",
"sea anemone\n",
"brain coral\n",
"flatworm\n",
"nematode\n",
"conch\n",
"snail\n",
"slug\n",
"sea slug\n",
"chiton\n",
"sea urchin\n",
"sea cucumber\n",
"iron\n",
"espresso maker\n",
"microwave\n",
"Dutch oven\n",
"rotisserie\n",
"toaster\n",
"waffle iron\n",
"vacuum\n",
"dishwasher\n",
"refrigerator\n",
"washer\n",
"Crock Pot\n",
"frying pan\n",
"wok\n",
"caldron\n",
"coffeepot\n",
"teapot\n",
"spatula\n",
"altar\n",
"triumphal arch\n",
"patio\n",
"steel arch bridge\n",
"suspension bridge\n",
"viaduct\n",
"barn\n",
"greenhouse\n",
"palace\n",
"monastery\n",
"library\n",
"apiary\n",
"boathouse\n",
"church\n",
"mosque\n",
"stupa\n",
"planetarium\n",
"restaurant\n",
"cinema\n",
"home theater\n",
"lumbermill\n",
"coil\n",
"obelisk\n",
"totem pole\n",
"castle\n",
"prison\n",
"grocery store\n",
"bakery\n",
"barbershop\n",
"bookshop\n",
"butcher shop\n",
"confectionery\n",
"shoe shop\n",
"tobacco shop\n",
"toyshop\n",
"fountain\n",
"cliff dwelling\n",
"yurt\n",
"dock\n",
"brass\n",
"megalith\n",
"bannister\n",
"breakwater\n",
"dam\n",
"chainlink fence\n",
"picket fence\n",
"worm fence\n",
"stone wall\n",
"grille\n",
"sliding door\n",
"turnstile\n",
"mountain tent\n",
"scoreboard\n",
"honeycomb\n",
"plate rack\n",
"pedestal\n",
"beacon\n",
"mashed potato\n",
"bell pepper\n",
"head cabbage\n",
"broccoli\n",
"cauliflower\n",
"zucchini\n",
"spaghetti squash\n",
"acorn squash\n",
"butternut squash\n",
"cucumber\n",
"artichoke\n",
"cardoon\n",
"mushroom\n",
"shower curtain\n",
"jean\n",
"carton\n",
"handkerchief\n",
"sandal\n",
"ashcan\n",
"safe\n",
"plate\n",
"necklace\n",
"croquet ball\n",
"fur coat\n",
"thimble\n",
"pajama\n",
"running shoe\n",
"cocktail shaker\n",
"chest\n",
"manhole cover\n",
"modem\n",
"tub\n",
"tray\n",
"balance beam\n",
"bagel\n",
"prayer rug\n",
"kimono\n",
"hot pot\n",
"whiskey jug\n",
"knee pad\n",
"book jacket\n",
"spindle\n",
"ski mask\n",
"beer bottle\n",
"crash helmet\n",
"bottlecap\n",
"tile roof\n",
"mask\n",
"maillot\n",
"Petri dish\n",
"football helmet\n",
"bathing cap\n",
"teddy bear\n",
"holster\n",
"pop bottle\n",
"photocopier\n",
"vestment\n",
"crossword puzzle\n",
"golf ball\n",
"trifle\n",
"suit\n",
"water tower\n",
"feather boa\n",
"cloak\n",
"red wine\n",
"drumstick\n",
"shield\n",
"Christmas stocking\n",
"hoopskirt\n",
"menu\n",
"stage\n",
"bonnet\n",
"meat loaf\n",
"baseball\n",
"face powder\n",
"scabbard\n",
"sunscreen\n",
"beer glass\n",
"hen-of-the-woods\n",
"guacamole\n",
"lampshade\n",
"wool\n",
"hay\n",
"bow tie\n",
"mailbag\n",
"water jug\n",
"bucket\n",
"dishrag\n",
"soup bowl\n",
"eggnog\n",
"mortar\n",
"trench coat\n",
"paddle\n",
"chain\n",
"swab\n",
"mixing bowl\n",
"potpie\n",
"wine bottle\n",
"shoji\n",
"bulletproof vest\n",
"drilling platform\n",
"binder\n",
"cardigan\n",
"sweatshirt\n",
"pot\n",
"birdhouse\n",
"hamper\n",
"ping-pong ball\n",
"pencil box\n",
"pay-phone\n",
"consomme\n",
"apron\n",
"punching bag\n",
"backpack\n",
"groom\n",
"bearskin\n",
"pencil sharpener\n",
"broom\n",
"mosquito net\n",
"abaya\n",
"mortarboard\n",
"poncho\n",
"crutch\n",
"Polaroid camera\n",
"space bar\n",
"cup\n",
"racket\n",
"traffic light\n",
"quill\n",
"radio\n",
"dough\n",
"cuirass\n",
"military uniform\n",
"lipstick\n",
"shower cap\n",
"monitor\n",
"oscilloscope\n",
"mitten\n",
"brassiere\n",
"French loaf\n",
"vase\n",
"milk can\n",
"rugby ball\n",
"paper towel\n",
"earthstar\n",
"envelope\n",
"miniskirt\n",
"cowboy hat\n",
"trolleybus\n",
"perfume\n",
"bathtub\n",
"hotdog\n",
"coral fungus\n",
"bullet train\n",
"pillow\n",
"toilet tissue\n",
"cassette\n",
"carpenter's kit\n",
"ladle\n",
"stinkhorn\n",
"lotion\n",
"hair spray\n",
"academic gown\n",
"dome\n",
"crate\n",
"wig\n",
"burrito\n",
"pill bottle\n",
"chain mail\n",
"theater curtain\n",
"window shade\n",
"barrel\n",
"washbasin\n",
"ballpoint\n",
"basketball\n",
"bath towel\n",
"cowboy boot\n",
"gown\n",
"window screen\n",
"agaric\n",
"cellular telephone\n",
"nipple\n",
"barbell\n",
"mailbox\n",
"lab coat\n",
"fire screen\n",
"minibus\n",
"packet\n",
"maze\n",
"pole\n",
"horizontal bar\n",
"sombrero\n",
"pickelhaube\n",
"rain barrel\n",
"wallet\n",
"cassette player\n",
"comic book\n",
"piggy bank\n",
"street sign\n",
"bell cote\n",
"fountain pen\n",
"Windsor tie\n",
"volleyball\n",
"overskirt\n",
"sarong\n",
"purse\n",
"bolo tie\n",
"bib\n",
"parachute\n",
"sleeping bag\n",
"television\n",
"swimming trunks\n",
"measuring cup\n",
"espresso\n",
"pizza\n",
"breastplate\n",
"shopping basket\n",
"wooden spoon\n",
"saltshaker\n",
"chocolate sauce\n",
"ballplayer\n",
"goblet\n",
"gyromitra\n",
"stretcher\n",
"water bottle\n",
"dial telephone\n",
"soap dispenser\n",
"jersey\n",
"school bus\n",
"jigsaw puzzle\n",
"plastic bag\n",
"reflex camera\n",
"diaper\n",
"Band Aid\n",
"ice lolly\n",
"velvet\n",
"tennis ball\n",
"gasmask\n",
"doormat\n",
"Loafer\n",
"ice cream\n",
"pretzel\n",
"quilt\n",
"maillot\n",
"tape player\n",
"clog\n",
"iPod\n",
"bolete\n",
"scuba diver\n",
"pitcher\n",
"matchstick\n",
"bikini\n",
"sock\n",
"CD player\n",
"lens cap\n",
"thatch\n",
"vault\n",
"beaker\n",
"bubble\n",
"cheeseburger\n",
"parallel bars\n",
"flagpole\n",
"coffee mug\n",
"rubber eraser\n",
"stole\n",
"carbonara\n",
"dumbbell\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
"OVERFLOW!\n",
};
